MODULE Student;
REQUIRE Teachers, Class;

// Объявление классов
CLASS Student;

// Объявление свойств
class 'Класс' = DATA INTEGER(Student);
number 'п/п' = DATA INTEGER(Student);
number = PARTITION SUM 1 ORDER d BY number(d) CHARWIDTH 1;
name 'ФИО' = DATA STRING[50](Student);
quantity 'Количество учеников в классе' = DATA INTEGER (Class);
quantity = GROUP SUM 1 BY quantity(Class class);

// Объявление формы
FORM studentForm 'Ученики'
    OBJECTS s = Student
    PROPERTIES(s) number, name, NEW, EDIT, DELETE
;

// Добавление формы в навигатор
NAVIGATOR {
    NEW studentForm;
}

// Расширение формы редактирования
EXTEND FORM classForm
    OBJECTS l = Class
    PROPERTIES(l) quantity, NEW, EDIT, DELETE
    OBJECTS f = Student
    PROPERTIES(f) number, name, NEW, EDIT, DELETE
;

// Расширение формы списка
EXTEND FORM classForm
    OBJECTS a = Class
    PROPERTIES(a) READONLY quantity
;
